default:
  image:  ubuntu:latest

stage:
  - program

program:
  stage: program
  before_script:
    - sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list
    - apt-get update && apt-get install -y build-essential gcc python3 python3-pip
    - pip install wget -i https://mirrors.aliyun.com/pypi/simple/
    - pip install biopython -i https://mirrors.aliyun.com/pypi/simple/
    - tar -xvf hmmer.tar.gz
    - cd hmmer-3.3.2
    - ./configure
    - make
    - make install
    - export PATH="$PATH:~/hmmer-3.3.2/bin"
    - cd ..
  script:
    - python3 main.py
  artifacts:
    paths:
      - model.hmm
      - PFseed.txt
      - result.out
      - id_list.txt
      - protein_for_target_id.fasta
  only:
    - main