default:
  image:  ubuntu:latest

stages:
  - hmmer_search
  - extract_id
  - extract_sequence

hmmer_search:
  stage: hmmer_search
  before_script:
    - sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list
    - apt-get update && apt-get install -y build-essential gcc python3 python3-pip
    - pip install requests -i https://mirrors.aliyun.com/pypi/simple/
    - tar -xvf hmmer.tar.gz
    - cd hmmer-3.3.2
    - ./configure
    - make
    - make install
    - export PATH="$PATH:~/hmmer-3.3.2/bin"
    - cd ..
  script:
    - python3 data_preparation.py
    - python3 hmmer.py
  artifacts:
    paths:
      - build.hmm
      - PFseed.txt
      - result.out
  only:
    - main

extract_id:
  stage: extract_id
  before_script:
    - sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list
    - apt-get update && apt-get install python3 -y
  script:
    - chmod +x extract_id.py
    - python3 extract_id.py
  artifacts:
    paths:
      - id_list.txt
  only:
    - main

extract_sequence:
  stage: extract_sequence
  before_script:
    - sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list
    - apt-get update && apt-get install python3-pip -y
    - pip install biopython -i https://mirrors.aliyun.com/pypi/simple/
  script:
    - chmod +x extract_sequence.py
    - python3 extract_sequence.py
  artifacts:
    paths:
      - protein_for_target_id.fasta
  only:
    - main
