name: CI

on:
  push:
    branches:
      - main

jobs:
  hmmer_search:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential gcc python3 python3-pip
          pip install requests
          tar -xvf hmmer.tar.gz
          cd hmmer-3.3.2
          ./configure
          make
          sudo make install
          export PATH="$PATH:~/hmmer-3.3.2/bin"
          cd ..
      - name: Run scripts
        run: |
          python3 data_preparation.py
          python3 hmmer.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hmmer-out
          path: |
            build.hmm
            PFseed.txt
            result.out


  extract_id:
    needs: hmmer_search
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download result.out
        uses: actions/download-artifact@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3 -y

      - name: Run scripts
        run: |
          sudo chmod +x extract_id.py
          python3 extract_id.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: id-list
          path: |
            id_list.txt

  extract_sequence:
    needs: extract_id
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download id_list.txt
        uses: actions/download-artifact@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3-pip -y
          pip install biopython

      - name: Run scripts
        run: |
          sudo chmod +x extract_sequence.py
          python3 extract_sequence.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sequence-data
          path: |
            protein_for_target_id.fasta